"use client"
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { TaskProvider } from '@/context/TaskContext';
import Head from 'next/head';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
      </Head>

      <body className={`bg-white`} suppressHydrationWarning={true}>
        <TaskProvider>
          {children}
        </TaskProvider>
      </body>

    </html>
  )
}
